namespace:
  name: k8s-30d
  create: true
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

images:
  busybox: busybox:1.36.1
  nginx: nginx:1.27-alpine
  restrictedNginx: nginxinc/nginx-unprivileged:1.27-alpine
  hpaExample: registry.k8s.io/hpa-example:latest
  stress: polinux/stress:1.0.4

labs:
  web:
    enabled: false
    replicas: 3

  podInternals:
    enabled: false

  scheduling:
    enabled: false
    replicas: 3
    priorityClassName: k8s-30d-important

  storage:
    enabled: false
    size: 1Gi
    storageClassName: ""

  workloads:
    enabled: false
    statefulSetReplicas: 3
    cronSchedule: "*/5 * * * *"

  rbac:
    enabled: false

  security:
    enabled: false

  scalingReliability:
    enabled: false
    replicas: 2
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

  failures:
    enabled: false

  crd:
    enabled: false
    widget:
      enabled: false
      message: reconcile-me
      replicas: 2
