{{- if .Values.labs.podInternals.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: pod-internals
  namespace: {{ include "kubernetes-internals.namespace" . }}
  labels:
    app: pod-internals
    {{- include "kubernetes-internals.labels" . | nindent 4 }}
spec:
  restartPolicy: Always
  initContainers:
    - name: initialize
      image: {{ .Values.images.busybox | quote }}
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo initialized-at-$(date -Iseconds) > /work/status && sleep 2"]
      volumeMounts:
        - name: work
          mountPath: /work
  containers:
    - name: application
      image: {{ .Values.images.busybox | quote }}
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do echo app-$(date -Iseconds) >> /work/app.log; sleep 5; done"]
      resources:
        requests: {cpu: 5m, memory: 8Mi}
        limits: {cpu: 50m, memory: 32Mi}
      volumeMounts:
        - name: work
          mountPath: /work
    - name: log-sidecar
      image: {{ .Values.images.busybox | quote }}
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "touch /work/app.log; tail -n+1 -F /work/app.log"]
      resources:
        requests: {cpu: 5m, memory: 8Mi}
        limits: {cpu: 50m, memory: 32Mi}
      volumeMounts:
        - name: work
          mountPath: /work
  volumes:
    - name: work
      emptyDir: {}
{{- end }}
